if( !("rvest" %in% installed.packages()) )
  install.packages("rvest")
if( !("tidyverse" %in% installed.packages()) )
  install.packages("tidyverse")
if( !("dplyr" %in% installed.packages()) )
  install.packages("dplyr")
if( !("tidyr" %in% installed.packages()) )
  install.packages("tidyr")
if( !("caret" %in% installed.packages()) )
  install.packages("caret")
if( !("knitr" %in% installed.packages()) )
  install.packages("knitr")
if( !("naniar" %in% installed.packages()) )
  install.packages("naniar")
if( !("ggplot2" %in% installed.packages()) )
  install.packages("ggplot2")
library("rvest")
library("tidyverse")
library("dplyr")
library("tidyr")
library("caret")
library("knitr")
library("naniar")
library("ggplot2")
