---
title: "School District Funding and Impact " #replace the title with something short and catchy to represent your project
subtitle: "Brenndan Olson's Data Science Portfolio" #replace blank with your name
output:
  html_document:
    df_print: paged
---

## Abstract

This portfolio will document the investigation of public school district financial data, and its affect on performance. It is pretty obvious that more spending in schools will yield more successful students, and data is collected and analyzed to try and support that claim. After the data is collected, multiple linear regression modeling is done to find correlation in the data.
  
  
### 1. Discovery and Data Preparation

In this first phase we are going to be finding a dataset, and cleaning up the data to make it more suited for statistical analysis. Early investigations will also be done on the data collected.
[First Phase](https://introdsci.github.io/DataScience-bolson10/deliverable1.html)
### 2. Model Planning and Building

After finding some initial data, more is supplemented to create a model to predict a district's ranking.  
[Second Phase](https://introdsci.github.io/DataScience-bolson10/deliverable2.html)

### 3. Results and Operationalization

More data is collected, and a better model is built. The implications of this data are also discussed.
[Third Phase](https://introdsci.github.io/DataScience-bolson10/deliverable3.html)

